spring.application.name=Dodo-Pizza-Project

server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/dodo-pizza-db
spring.datasource.username=postgres
spring.datasource.password=satorugod1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
server.error.include-message=always
server.error.include-binding-errors=always